coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "ci/**"
  - "proto/**"
  - "tests/**"
  - "**/migrations/**"
  - "**/target/**"
  - "**/*.proto"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
