[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2.0.17"
urlencoding = "2.1.3"

cortexmap-core = { path = "crates/cortexmap-core" }
