# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/cortexmap-infra/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

#[migrations_directory]
#dir = "/home/ssdd/RustroverProjects/capstone26-drkim-proto1/migrations"
