# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comm_pb2 as comm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in comm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainRegionServiceStub(object):
    """gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchBrainRegion = channel.unary_unary(
                '/comm.BrainRegionService/SearchBrainRegion',
                request_serializer=comm__pb2.SearchBrainRegionRequest.SerializeToString,
                response_deserializer=comm__pb2.SearchBrainRegionResponse.FromString,
                _registered_method=True)
        self.GetAllBrainRegions = channel.unary_unary(
                '/comm.BrainRegionService/GetAllBrainRegions',
                request_serializer=comm__pb2.GetAllBrainRegionsRequest.SerializeToString,
                response_deserializer=comm__pb2.GetAllBrainRegionsResponse.FromString,
                _registered_method=True)


class BrainRegionServiceServicer(object):
    """gRPC service definition
    """

    def SearchBrainRegion(self, request, context):
        """Search for a specific brain region entry by query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBrainRegions(self, request, context):
        """Retrieve all available brain region entries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainRegionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchBrainRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBrainRegion,
                    request_deserializer=comm__pb2.SearchBrainRegionRequest.FromString,
                    response_serializer=comm__pb2.SearchBrainRegionResponse.SerializeToString,
            ),
            'GetAllBrainRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBrainRegions,
                    request_deserializer=comm__pb2.GetAllBrainRegionsRequest.FromString,
                    response_serializer=comm__pb2.GetAllBrainRegionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comm.BrainRegionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('comm.BrainRegionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainRegionService(object):
    """gRPC service definition
    """

    @staticmethod
    def SearchBrainRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comm.BrainRegionService/SearchBrainRegion',
            comm__pb2.SearchBrainRegionRequest.SerializeToString,
            comm__pb2.SearchBrainRegionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBrainRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comm.BrainRegionService/GetAllBrainRegions',
            comm__pb2.GetAllBrainRegionsRequest.SerializeToString,
            comm__pb2.GetAllBrainRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
