# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x12\x04\x63omm\")\n\x18SearchBrainRegionRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1b\n\x19GetAllBrainRegionsRequest\"\xfb\x01\n\x10\x42rainRegionEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\x12\x17\n\x0fquery_timestamp\x18\x03 \x01(\x03\x12\x13\n\x0bregion_name\x18\x04 \x01(\t\x12\x12\n\nhemisphere\x18\x05 \x01(\t\x12\x0c\n\x04lobe\x18\x06 \x01(\t\x12\x19\n\x11\x61natomical_region\x18\x07 \x01(\t\x12\x1c\n\x14\x66unction_description\x18\x08 \x01(\t\x12\x1b\n\x13\x64isease_description\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\x03\x12\x12\n\nupdated_at\x18\x0b \x01(\x03\"k\n\x19SearchBrainRegionResponse\x12\'\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x16.comm.BrainRegionEntry\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x81\x01\n\x1aGetAllBrainRegionsResponse\x12\'\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x16.comm.BrainRegionEntry\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2\xc3\x01\n\x12\x42rainRegionService\x12T\n\x11SearchBrainRegion\x12\x1e.comm.SearchBrainRegionRequest\x1a\x1f.comm.SearchBrainRegionResponse\x12W\n\x12GetAllBrainRegions\x12\x1f.comm.GetAllBrainRegionsRequest\x1a .comm.GetAllBrainRegionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHBRAINREGIONREQUEST']._serialized_start=20
  _globals['_SEARCHBRAINREGIONREQUEST']._serialized_end=61
  _globals['_GETALLBRAINREGIONSREQUEST']._serialized_start=63
  _globals['_GETALLBRAINREGIONSREQUEST']._serialized_end=90
  _globals['_BRAINREGIONENTRY']._serialized_start=93
  _globals['_BRAINREGIONENTRY']._serialized_end=344
  _globals['_SEARCHBRAINREGIONRESPONSE']._serialized_start=346
  _globals['_SEARCHBRAINREGIONRESPONSE']._serialized_end=453
  _globals['_GETALLBRAINREGIONSRESPONSE']._serialized_start=456
  _globals['_GETALLBRAINREGIONSRESPONSE']._serialized_end=585
  _globals['_BRAINREGIONSERVICE']._serialized_start=588
  _globals['_BRAINREGIONSERVICE']._serialized_end=783
# @@protoc_insertion_point(module_scope)
