### Stop all workers
POST http://ec2-3-88-176-142.compute-1.amazonaws.com/api/queue/workers/stop
Content-Type: application/json

{
  "worker_ids": []
}

### Stop specific workers by ID
POST http://localhost:8080/api/queue/workers/stop
Content-Type: application/json

{
  "worker_ids": ["worker-id-1", "worker-id-2"]
}
