syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";

package com.cortexmap;

message  RegionID {
  int32 id = 1;
}

message Acronym {
  string acronym = 1;
}
message Uuid {
  string value = 1;
}

// Request message for searching a specific brain region entry
// List of IDs can be fetched using ListBrainRegions RPC
message SearchBrainRegionRequest {
  Uuid id = 1;
}

// When the region information is updated overtime,
// there will be multiple entries for the same region,
// and this message will be used to return all the entries for a specific region.
message BrainRegionList {
  repeated BrainRegionEntry entries = 1;
}

message BrainRegionEntry {
  RegionID region_id = 1;
  string description = 2;
  google.protobuf.Timestamp created_at = 10;  // Unix timestamp in milliseconds
}

message SearchBrainRegionResponse {
  BrainRegionEntry entry = 1;
}

enum Status {
  FETCHER_QUEUE = 0;
  FETCHING = 1;
  INDEX_QUEUE = 2;
  INDEXING = 3;
  GENERATING = 4;
  DONE = 5;
}

message RGB {
  int32 r = 1;
  int32 g = 2;
  int32 b = 3;
}

message RegionMapping {
  Uuid id = 1;

  // Data defined in the excel sheet
  RegionID region_id = 2;
  Status status = 3;
  RGB color = 4;
  int32 structure_order = 5;
  RegionID parent_region_id = 6;
  Acronym acronym = 7;
  Acronym parent_acronym = 8;
}

message BrainRegionListResponse {
  repeated RegionMapping regions = 1;
}

message StatusRequest {
  Uuid id = 1;
}

message StatusResponse {
  Status status = 1;
}

service BrainRegionService {
  // Search for a specific brain region entry by query
  rpc SearchBrainRegion(SearchBrainRegionRequest) returns (SearchBrainRegionResponse) {
    option (google.api.http) = {
      post: "/api/search"
      body: "*"
    };
  }

  // List all brain region entries, which can be used to fetch the list of IDs for searching specific entries.
  rpc ListBrainRegions(google.protobuf.Empty) returns (BrainRegionListResponse) {
    option (google.api.http) = {
      get: "/api/list"
    };
  }

  // Check the status of a specific brain region entry by ID,
  // which can be used to track the progress of fetching, indexing, and generating the data for that region.
  rpc Status(StatusRequest) returns (StatusResponse) {
    option (google.api.http) = {
      post: "/api/status"
      body: "*"
    };
  }
}
